

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."accounts_organization" (
    "id" "uuid" NOT NULL,
    "type" character varying(16) NOT NULL,
    "name" character varying(200) NOT NULL,
    "country_code" character varying(2),
    "created_at" timestamp with time zone NOT NULL,
    "added_by_id" integer,
    "address" "text",
    "phone" character varying(32),
    "status" character varying(16) NOT NULL,
    "tax_id" character varying(64),
    "updated_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."accounts_organization" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."accounts_profile" (
    "id" "uuid" NOT NULL,
    "role" character varying(16) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "organization_id" "uuid",
    "user_id" integer NOT NULL,
    CONSTRAINT "org_required_for_non_candidates" CHECK (((("organization_id" IS NULL) AND (("role")::"text" = 'candidate'::"text")) OR ((NOT (("role")::"text" = 'candidate'::"text")) AND ("organization_id" IS NOT NULL))))
);


ALTER TABLE "public"."accounts_profile" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."applications_application" (
    "id" "uuid" NOT NULL,
    "source" character varying(64),
    "created_at" timestamp with time zone NOT NULL,
    "candidate_id" "uuid" NOT NULL,
    "job_id" "uuid" NOT NULL,
    "owner_id" "uuid",
    "current_status_id" character varying(32) NOT NULL
);


ALTER TABLE "public"."applications_application" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."applications_applicationevent" (
    "id" "uuid" NOT NULL,
    "type" character varying(64) NOT NULL,
    "payload" "jsonb" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "application_id" "uuid" NOT NULL,
    "created_by_id" "uuid"
);


ALTER TABLE "public"."applications_applicationevent" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."applications_note" (
    "id" "uuid" NOT NULL,
    "body" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "application_id" "uuid",
    "candidate_id" "uuid",
    "created_by_id" "uuid"
);


ALTER TABLE "public"."applications_note" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."applications_status" (
    "code" character varying(32) NOT NULL,
    "label" character varying(64) NOT NULL,
    "category" character varying(32) NOT NULL
);


ALTER TABLE "public"."applications_status" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."auth_group" (
    "id" integer NOT NULL,
    "name" character varying(150) NOT NULL
);


ALTER TABLE "public"."auth_group" OWNER TO "postgres";


ALTER TABLE "public"."auth_group" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_group_permissions" (
    "id" bigint NOT NULL,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_group_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_group_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_group_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_permission" (
    "id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" character varying(100) NOT NULL
);


ALTER TABLE "public"."auth_permission" OWNER TO "postgres";


ALTER TABLE "public"."auth_permission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user" (
    "id" integer NOT NULL,
    "password" character varying(128) NOT NULL,
    "last_login" timestamp with time zone,
    "is_superuser" boolean NOT NULL,
    "username" character varying(150) NOT NULL,
    "first_name" character varying(150) NOT NULL,
    "last_name" character varying(150) NOT NULL,
    "email" character varying(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."auth_user" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."auth_user_groups" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "group_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_groups" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_groups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_groups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."auth_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."auth_user_user_permissions" (
    "id" bigint NOT NULL,
    "user_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);


ALTER TABLE "public"."auth_user_user_permissions" OWNER TO "postgres";


ALTER TABLE "public"."auth_user_user_permissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."auth_user_user_permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."candidates_candidate" (
    "id" "uuid" NOT NULL,
    "first_name" character varying(80) NOT NULL,
    "last_name" character varying(80) NOT NULL,
    "email" character varying(254),
    "phone" character varying(40),
    "passport_no" character varying(40),
    "birth_date" "date",
    "gender" character varying(20),
    "created_at" timestamp with time zone NOT NULL,
    "nationality_id" character varying(2),
    "profile_id" "uuid"
);


ALTER TABLE "public"."candidates_candidate" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."candidates_candidateexperience" (
    "id" "uuid" NOT NULL,
    "employer" character varying(120) NOT NULL,
    "role" character varying(120) NOT NULL,
    "start_date" "date",
    "end_date" "date",
    "description" "text" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "candidate_id" "uuid" NOT NULL
);


ALTER TABLE "public"."candidates_candidateexperience" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."candidates_candidateskill" (
    "id" "uuid" NOT NULL,
    "skill" character varying(80) NOT NULL,
    "level" character varying(30),
    "created_at" timestamp with time zone NOT NULL,
    "candidate_id" "uuid" NOT NULL
);


ALTER TABLE "public"."candidates_candidateskill" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."directory_country" (
    "code" character varying(2) NOT NULL,
    "name" character varying(100) NOT NULL,
    "dial_code" character varying(6)
);


ALTER TABLE "public"."directory_country" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."django_admin_log" (
    "id" integer NOT NULL,
    "action_time" timestamp with time zone NOT NULL,
    "object_id" "text",
    "object_repr" character varying(200) NOT NULL,
    "action_flag" smallint NOT NULL,
    "change_message" "text" NOT NULL,
    "content_type_id" integer,
    "user_id" integer NOT NULL,
    CONSTRAINT "django_admin_log_action_flag_check" CHECK (("action_flag" >= 0))
);


ALTER TABLE "public"."django_admin_log" OWNER TO "postgres";


ALTER TABLE "public"."django_admin_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_admin_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_content_type" (
    "id" integer NOT NULL,
    "app_label" character varying(100) NOT NULL,
    "model" character varying(100) NOT NULL
);


ALTER TABLE "public"."django_content_type" OWNER TO "postgres";


ALTER TABLE "public"."django_content_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_content_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_migrations" (
    "id" bigint NOT NULL,
    "app" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_migrations" OWNER TO "postgres";


ALTER TABLE "public"."django_migrations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."django_migrations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."django_session" (
    "session_key" character varying(40) NOT NULL,
    "session_data" "text" NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."django_session" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."documents_document" (
    "id" "uuid" NOT NULL,
    "owner_type" character varying(16) NOT NULL,
    "owner_id" "uuid" NOT NULL,
    "kind" character varying(32) NOT NULL,
    "storage_path" character varying(512) NOT NULL,
    "metadata" "jsonb" NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "uploaded_by_id" "uuid"
);


ALTER TABLE "public"."documents_document" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."finance_payment" (
    "id" "uuid" NOT NULL,
    "amount" numeric(12,2) NOT NULL,
    "currency" character varying(3) NOT NULL,
    "method" character varying(32),
    "paid_at" timestamp with time zone,
    "reference" character varying(128),
    "application_id" "uuid" NOT NULL
);


ALTER TABLE "public"."finance_payment" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."jobs_job" (
    "id" "uuid" NOT NULL,
    "title" character varying(160) NOT NULL,
    "description" "text" NOT NULL,
    "salary_min" integer,
    "salary_max" integer,
    "currency" character varying(3),
    "status" character varying(24) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "country_id" character varying(2),
    "created_by_id" integer NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "updated_by_id" integer NOT NULL,
    "vacancies_filled" integer NOT NULL,
    "vacancies_initial" integer,
    "vacancies_limit" integer,
    CONSTRAINT "job_vac_filled_nonneg" CHECK (("vacancies_filled" >= 0)),
    CONSTRAINT "job_vac_initial_nonneg" CHECK ((("vacancies_initial" >= 0) OR ("vacancies_initial" IS NULL))),
    CONSTRAINT "job_vac_limit_gte_filled" CHECK ((("vacancies_limit" IS NULL) OR ("vacancies_limit" >= "vacancies_filled"))),
    CONSTRAINT "job_vac_limit_nonneg" CHECK ((("vacancies_limit" >= 0) OR ("vacancies_limit" IS NULL))),
    CONSTRAINT "jobs_job_vacancies_filled_check" CHECK (("vacancies_filled" >= 0)),
    CONSTRAINT "jobs_job_vacancies_initial_check" CHECK (("vacancies_initial" >= 0)),
    CONSTRAINT "jobs_job_vacancies_limit_check" CHECK (("vacancies_limit" >= 0))
);


ALTER TABLE "public"."jobs_job" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."jobs_jobimage" (
    "id" "uuid" NOT NULL,
    "image" character varying(100) NOT NULL,
    "caption" character varying(200) NOT NULL,
    "uploaded_at" timestamp with time zone NOT NULL,
    "job_id" "uuid" NOT NULL
);


ALTER TABLE "public"."jobs_jobimage" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."token_blacklist_blacklistedtoken" (
    "id" bigint NOT NULL,
    "blacklisted_at" timestamp with time zone NOT NULL,
    "token_id" bigint NOT NULL
);


ALTER TABLE "public"."token_blacklist_blacklistedtoken" OWNER TO "postgres";


ALTER TABLE "public"."token_blacklist_blacklistedtoken" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."token_blacklist_blacklistedtoken_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."token_blacklist_outstandingtoken" (
    "id" bigint NOT NULL,
    "token" "text" NOT NULL,
    "created_at" timestamp with time zone,
    "expires_at" timestamp with time zone NOT NULL,
    "user_id" integer,
    "jti" character varying(255) NOT NULL
);


ALTER TABLE "public"."token_blacklist_outstandingtoken" OWNER TO "postgres";


ALTER TABLE "public"."token_blacklist_outstandingtoken" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."token_blacklist_outstandingtoken_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."accounts_organization"
    ADD CONSTRAINT "accounts_organization_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."accounts_organization"
    ADD CONSTRAINT "accounts_organization_type_name_67b1ab47_uniq" UNIQUE ("type", "name");



ALTER TABLE ONLY "public"."accounts_profile"
    ADD CONSTRAINT "accounts_profile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."accounts_profile"
    ADD CONSTRAINT "accounts_profile_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."applications_application"
    ADD CONSTRAINT "applications_application_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applications_applicationevent"
    ADD CONSTRAINT "applications_applicationevent_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applications_note"
    ADD CONSTRAINT "applications_note_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applications_status"
    ADD CONSTRAINT "applications_status_pkey" PRIMARY KEY ("code");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_group"
    ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");



ALTER TABLE ONLY "public"."auth_user"
    ADD CONSTRAINT "auth_user_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."candidates_candidate"
    ADD CONSTRAINT "candidates_candidate_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidates_candidate"
    ADD CONSTRAINT "candidates_candidate_profile_id_key" UNIQUE ("profile_id");



ALTER TABLE ONLY "public"."candidates_candidateexperience"
    ADD CONSTRAINT "candidates_candidateexperience_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."candidates_candidateskill"
    ADD CONSTRAINT "candidates_candidateskill_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."directory_country"
    ADD CONSTRAINT "directory_country_pkey" PRIMARY KEY ("code");



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");



ALTER TABLE ONLY "public"."django_content_type"
    ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_migrations"
    ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."django_session"
    ADD CONSTRAINT "django_session_pkey" PRIMARY KEY ("session_key");



ALTER TABLE ONLY "public"."documents_document"
    ADD CONSTRAINT "documents_document_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."finance_payment"
    ADD CONSTRAINT "finance_payment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."jobs_job"
    ADD CONSTRAINT "jobs_job_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."jobs_jobimage"
    ADD CONSTRAINT "jobs_jobimage_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."token_blacklist_blacklistedtoken"
    ADD CONSTRAINT "token_blacklist_blacklistedtoken_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."token_blacklist_blacklistedtoken"
    ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_key" UNIQUE ("token_id");



ALTER TABLE ONLY "public"."token_blacklist_outstandingtoken"
    ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti");



ALTER TABLE ONLY "public"."token_blacklist_outstandingtoken"
    ADD CONSTRAINT "token_blacklist_outstandingtoken_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applications_application"
    ADD CONSTRAINT "uniq_application_per_job" UNIQUE ("candidate_id", "job_id");



CREATE INDEX "accounts_organization_added_by_id_4ade5a79" ON "public"."accounts_organization" USING "btree" ("added_by_id");



CREATE INDEX "accounts_profile_organization_id_c789c6e1" ON "public"."accounts_profile" USING "btree" ("organization_id");



CREATE INDEX "applications_application_candidate_id_3ff505d9" ON "public"."applications_application" USING "btree" ("candidate_id");



CREATE INDEX "applications_application_current_status_id_ec85b2fb" ON "public"."applications_application" USING "btree" ("current_status_id");



CREATE INDEX "applications_application_current_status_id_ec85b2fb_like" ON "public"."applications_application" USING "btree" ("current_status_id" "varchar_pattern_ops");



CREATE INDEX "applications_application_job_id_c031177c" ON "public"."applications_application" USING "btree" ("job_id");



CREATE INDEX "applications_application_owner_id_5b77f5bb" ON "public"."applications_application" USING "btree" ("owner_id");



CREATE INDEX "applications_applicationevent_application_id_c0588dda" ON "public"."applications_applicationevent" USING "btree" ("application_id");



CREATE INDEX "applications_applicationevent_created_by_id_a8dc5845" ON "public"."applications_applicationevent" USING "btree" ("created_by_id");



CREATE INDEX "applications_note_application_id_d7605945" ON "public"."applications_note" USING "btree" ("application_id");



CREATE INDEX "applications_note_candidate_id_38d564a2" ON "public"."applications_note" USING "btree" ("candidate_id");



CREATE INDEX "applications_note_created_by_id_539d5dcf" ON "public"."applications_note" USING "btree" ("created_by_id");



CREATE INDEX "applications_status_code_63316920_like" ON "public"."applications_status" USING "btree" ("code" "varchar_pattern_ops");



CREATE INDEX "auth_group_name_a6ea08ec_like" ON "public"."auth_group" USING "btree" ("name" "varchar_pattern_ops");



CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "public"."auth_group_permissions" USING "btree" ("group_id");



CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "public"."auth_group_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING "btree" ("content_type_id");



CREATE INDEX "auth_user_groups_group_id_97559544" ON "public"."auth_user_groups" USING "btree" ("group_id");



CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "public"."auth_user_groups" USING "btree" ("user_id");



CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "public"."auth_user_user_permissions" USING "btree" ("permission_id");



CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "public"."auth_user_user_permissions" USING "btree" ("user_id");



CREATE INDEX "auth_user_username_6821ab7c_like" ON "public"."auth_user" USING "btree" ("username" "varchar_pattern_ops");



CREATE INDEX "candidates_candidate_nationality_id_5cc6e8c9" ON "public"."candidates_candidate" USING "btree" ("nationality_id");



CREATE INDEX "candidates_candidate_nationality_id_5cc6e8c9_like" ON "public"."candidates_candidate" USING "btree" ("nationality_id" "varchar_pattern_ops");



CREATE INDEX "candidates_candidate_passport_no_3d9ce7ae" ON "public"."candidates_candidate" USING "btree" ("passport_no");



CREATE INDEX "candidates_candidate_passport_no_3d9ce7ae_like" ON "public"."candidates_candidate" USING "btree" ("passport_no" "varchar_pattern_ops");



CREATE INDEX "candidates_candidateexperience_candidate_id_cbd4b90c" ON "public"."candidates_candidateexperience" USING "btree" ("candidate_id");



CREATE INDEX "candidates_candidateskill_candidate_id_4f07b3fa" ON "public"."candidates_candidateskill" USING "btree" ("candidate_id");



CREATE INDEX "directory_country_code_9bc9b16c_like" ON "public"."directory_country" USING "btree" ("code" "varchar_pattern_ops");



CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "public"."django_admin_log" USING "btree" ("content_type_id");



CREATE INDEX "django_admin_log_user_id_c564eba6" ON "public"."django_admin_log" USING "btree" ("user_id");



CREATE INDEX "django_session_expire_date_a5c62663" ON "public"."django_session" USING "btree" ("expire_date");



CREATE INDEX "django_session_session_key_c0390e0f_like" ON "public"."django_session" USING "btree" ("session_key" "varchar_pattern_ops");



CREATE INDEX "documents_document_uploaded_by_id_cc1ba81a" ON "public"."documents_document" USING "btree" ("uploaded_by_id");



CREATE INDEX "finance_payment_application_id_ace07564" ON "public"."finance_payment" USING "btree" ("application_id");



CREATE INDEX "jobs_job_country_id_094e0f5d" ON "public"."jobs_job" USING "btree" ("country_id");



CREATE INDEX "jobs_job_country_id_094e0f5d_like" ON "public"."jobs_job" USING "btree" ("country_id" "varchar_pattern_ops");



CREATE INDEX "jobs_job_created_1b3a4d_idx" ON "public"."jobs_job" USING "btree" ("created_at");



CREATE INDEX "jobs_job_created_by_id_f3283268" ON "public"."jobs_job" USING "btree" ("created_by_id");



CREATE INDEX "jobs_job_organiz_01f5e3_idx" ON "public"."jobs_job" USING "btree" ("organization_id", "status");



CREATE INDEX "jobs_job_organization_id_7d00dcbc" ON "public"."jobs_job" USING "btree" ("organization_id");



CREATE INDEX "jobs_job_updated_by_id_516c635e" ON "public"."jobs_job" USING "btree" ("updated_by_id");



CREATE INDEX "jobs_jobimage_job_id_dc79519f" ON "public"."jobs_jobimage" USING "btree" ("job_id");



CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "public"."token_blacklist_outstandingtoken" USING "btree" ("jti" "varchar_pattern_ops");



CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "public"."token_blacklist_outstandingtoken" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."accounts_organization"
    ADD CONSTRAINT "accounts_organization_added_by_id_4ade5a79_fk_auth_user_id" FOREIGN KEY ("added_by_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."accounts_profile"
    ADD CONSTRAINT "accounts_profile_organization_id_c789c6e1_fk_accounts_" FOREIGN KEY ("organization_id") REFERENCES "public"."accounts_organization"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."accounts_profile"
    ADD CONSTRAINT "accounts_profile_user_id_49a85d32_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_applicationevent"
    ADD CONSTRAINT "applications_applica_application_id_c0588dda_fk_applicati" FOREIGN KEY ("application_id") REFERENCES "public"."applications_application"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_application"
    ADD CONSTRAINT "applications_applica_candidate_id_3ff505d9_fk_candidate" FOREIGN KEY ("candidate_id") REFERENCES "public"."candidates_candidate"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_applicationevent"
    ADD CONSTRAINT "applications_applica_created_by_id_a8dc5845_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "public"."accounts_profile"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_application"
    ADD CONSTRAINT "applications_applica_current_status_id_ec85b2fb_fk_applicati" FOREIGN KEY ("current_status_id") REFERENCES "public"."applications_status"("code") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_application"
    ADD CONSTRAINT "applications_applica_owner_id_5b77f5bb_fk_accounts_" FOREIGN KEY ("owner_id") REFERENCES "public"."accounts_profile"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_application"
    ADD CONSTRAINT "applications_application_job_id_c031177c_fk_jobs_job_id" FOREIGN KEY ("job_id") REFERENCES "public"."jobs_job"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_note"
    ADD CONSTRAINT "applications_note_application_id_d7605945_fk_applicati" FOREIGN KEY ("application_id") REFERENCES "public"."applications_application"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_note"
    ADD CONSTRAINT "applications_note_candidate_id_38d564a2_fk_candidate" FOREIGN KEY ("candidate_id") REFERENCES "public"."candidates_candidate"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."applications_note"
    ADD CONSTRAINT "applications_note_created_by_id_539d5dcf_fk_accounts_profile_id" FOREIGN KEY ("created_by_id") REFERENCES "public"."accounts_profile"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_group_permissions"
    ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_permission"
    ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "public"."auth_group"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_groups"
    ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "public"."auth_permission"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."auth_user_user_permissions"
    ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."candidates_candidateskill"
    ADD CONSTRAINT "candidates_candidate_candidate_id_4f07b3fa_fk_candidate" FOREIGN KEY ("candidate_id") REFERENCES "public"."candidates_candidate"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."candidates_candidateexperience"
    ADD CONSTRAINT "candidates_candidate_candidate_id_cbd4b90c_fk_candidate" FOREIGN KEY ("candidate_id") REFERENCES "public"."candidates_candidate"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."candidates_candidate"
    ADD CONSTRAINT "candidates_candidate_nationality_id_5cc6e8c9_fk_directory" FOREIGN KEY ("nationality_id") REFERENCES "public"."directory_country"("code") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."candidates_candidate"
    ADD CONSTRAINT "candidates_candidate_profile_id_72776f3a_fk_accounts_profile_id" FOREIGN KEY ("profile_id") REFERENCES "public"."accounts_profile"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."django_admin_log"
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."documents_document"
    ADD CONSTRAINT "documents_document_uploaded_by_id_cc1ba81a_fk_accounts_" FOREIGN KEY ("uploaded_by_id") REFERENCES "public"."accounts_profile"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."finance_payment"
    ADD CONSTRAINT "finance_payment_application_id_ace07564_fk_applicati" FOREIGN KEY ("application_id") REFERENCES "public"."applications_application"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."jobs_job"
    ADD CONSTRAINT "jobs_job_country_id_094e0f5d_fk_directory_country_code" FOREIGN KEY ("country_id") REFERENCES "public"."directory_country"("code") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."jobs_job"
    ADD CONSTRAINT "jobs_job_created_by_id_f3283268_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."jobs_job"
    ADD CONSTRAINT "jobs_job_organization_id_7d00dcbc_fk_accounts_organization_id" FOREIGN KEY ("organization_id") REFERENCES "public"."accounts_organization"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."jobs_job"
    ADD CONSTRAINT "jobs_job_updated_by_id_516c635e_fk_auth_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."jobs_jobimage"
    ADD CONSTRAINT "jobs_jobimage_job_id_dc79519f_fk_jobs_job_id" FOREIGN KEY ("job_id") REFERENCES "public"."jobs_job"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."token_blacklist_blacklistedtoken"
    ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY ("token_id") REFERENCES "public"."token_blacklist_outstandingtoken"("id") DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."token_blacklist_outstandingtoken"
    ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_auth_user" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user"("id") DEFERRABLE INITIALLY DEFERRED;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";














































































































































































GRANT ALL ON TABLE "public"."accounts_organization" TO "anon";
GRANT ALL ON TABLE "public"."accounts_organization" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts_organization" TO "service_role";



GRANT ALL ON TABLE "public"."accounts_profile" TO "anon";
GRANT ALL ON TABLE "public"."accounts_profile" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts_profile" TO "service_role";



GRANT ALL ON TABLE "public"."applications_application" TO "anon";
GRANT ALL ON TABLE "public"."applications_application" TO "authenticated";
GRANT ALL ON TABLE "public"."applications_application" TO "service_role";



GRANT ALL ON TABLE "public"."applications_applicationevent" TO "anon";
GRANT ALL ON TABLE "public"."applications_applicationevent" TO "authenticated";
GRANT ALL ON TABLE "public"."applications_applicationevent" TO "service_role";



GRANT ALL ON TABLE "public"."applications_note" TO "anon";
GRANT ALL ON TABLE "public"."applications_note" TO "authenticated";
GRANT ALL ON TABLE "public"."applications_note" TO "service_role";



GRANT ALL ON TABLE "public"."applications_status" TO "anon";
GRANT ALL ON TABLE "public"."applications_status" TO "authenticated";
GRANT ALL ON TABLE "public"."applications_status" TO "service_role";



GRANT ALL ON TABLE "public"."auth_group" TO "anon";
GRANT ALL ON TABLE "public"."auth_group" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_group_permissions" TO "anon";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_group_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_group_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_permission" TO "anon";
GRANT ALL ON TABLE "public"."auth_permission" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_permission" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_permission_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user" TO "anon";
GRANT ALL ON TABLE "public"."auth_user" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user_groups" TO "anon";
GRANT ALL ON TABLE "public"."auth_user_groups" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user_groups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_groups_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "anon";
GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "authenticated";
GRANT ALL ON TABLE "public"."auth_user_user_permissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."auth_user_user_permissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."candidates_candidate" TO "anon";
GRANT ALL ON TABLE "public"."candidates_candidate" TO "authenticated";
GRANT ALL ON TABLE "public"."candidates_candidate" TO "service_role";



GRANT ALL ON TABLE "public"."candidates_candidateexperience" TO "anon";
GRANT ALL ON TABLE "public"."candidates_candidateexperience" TO "authenticated";
GRANT ALL ON TABLE "public"."candidates_candidateexperience" TO "service_role";



GRANT ALL ON TABLE "public"."candidates_candidateskill" TO "anon";
GRANT ALL ON TABLE "public"."candidates_candidateskill" TO "authenticated";
GRANT ALL ON TABLE "public"."candidates_candidateskill" TO "service_role";



GRANT ALL ON TABLE "public"."directory_country" TO "anon";
GRANT ALL ON TABLE "public"."directory_country" TO "authenticated";
GRANT ALL ON TABLE "public"."directory_country" TO "service_role";



GRANT ALL ON TABLE "public"."django_admin_log" TO "anon";
GRANT ALL ON TABLE "public"."django_admin_log" TO "authenticated";
GRANT ALL ON TABLE "public"."django_admin_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_admin_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_content_type" TO "anon";
GRANT ALL ON TABLE "public"."django_content_type" TO "authenticated";
GRANT ALL ON TABLE "public"."django_content_type" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_content_type_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_migrations" TO "anon";
GRANT ALL ON TABLE "public"."django_migrations" TO "authenticated";
GRANT ALL ON TABLE "public"."django_migrations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."django_migrations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."django_session" TO "anon";
GRANT ALL ON TABLE "public"."django_session" TO "authenticated";
GRANT ALL ON TABLE "public"."django_session" TO "service_role";



GRANT ALL ON TABLE "public"."documents_document" TO "anon";
GRANT ALL ON TABLE "public"."documents_document" TO "authenticated";
GRANT ALL ON TABLE "public"."documents_document" TO "service_role";



GRANT ALL ON TABLE "public"."finance_payment" TO "anon";
GRANT ALL ON TABLE "public"."finance_payment" TO "authenticated";
GRANT ALL ON TABLE "public"."finance_payment" TO "service_role";



GRANT ALL ON TABLE "public"."jobs_job" TO "anon";
GRANT ALL ON TABLE "public"."jobs_job" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs_job" TO "service_role";



GRANT ALL ON TABLE "public"."jobs_jobimage" TO "anon";
GRANT ALL ON TABLE "public"."jobs_jobimage" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs_jobimage" TO "service_role";



GRANT ALL ON TABLE "public"."token_blacklist_blacklistedtoken" TO "anon";
GRANT ALL ON TABLE "public"."token_blacklist_blacklistedtoken" TO "authenticated";
GRANT ALL ON TABLE "public"."token_blacklist_blacklistedtoken" TO "service_role";



GRANT ALL ON SEQUENCE "public"."token_blacklist_blacklistedtoken_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."token_blacklist_blacklistedtoken_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."token_blacklist_blacklistedtoken_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."token_blacklist_outstandingtoken" TO "anon";
GRANT ALL ON TABLE "public"."token_blacklist_outstandingtoken" TO "authenticated";
GRANT ALL ON TABLE "public"."token_blacklist_outstandingtoken" TO "service_role";



GRANT ALL ON SEQUENCE "public"."token_blacklist_outstandingtoken_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."token_blacklist_outstandingtoken_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."token_blacklist_outstandingtoken_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
