# Generated by Django 5.2.5 on 2025-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
