# Generated by Django 5.2.5 on 2025-08-27 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(blank=True, max_length=32, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.application')),
            ],
        ),
    ]
