# Generated by Django 5.2.5 on 2025-08-29 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_added_by_organization_address_and_more'),
        ('directory', '0002_country_dial_code'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancies_filled',
            field=models.PositiveIntegerField(default=0, help_text='System counter incremented on submit, decremented on reject/withdraw.'),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies_initial',
            field=models.PositiveIntegerField(blank=True, help_text='Original announced openings at create time.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Current cap of openings allowed to be filled.', null=True),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('vacancies_initial__gte', 0), ('vacancies_initial__isnull', True), _connector='OR'), name='job_vac_initial_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('vacancies_limit__gte', 0), ('vacancies_limit__isnull', True), _connector='OR'), name='job_vac_limit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('vacancies_filled__gte', 0)), name='job_vac_filled_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('vacancies_limit__isnull', True), ('vacancies_limit__gte', models.F('vacancies_filled')), _connector='OR'), name='job_vac_limit_gte_filled'),
        ),
    ]
